// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	login "github.com/Streamfair/common_proto/IdentityProvider/pb/login"
	register "github.com/Streamfair/common_proto/IdentityProvider/pb/register"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IdentityProviderClient is the client API for IdentityProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityProviderClient interface {
	LoginUserAccount(ctx context.Context, in *login.LoginUserAccountRequest, opts ...grpc.CallOption) (*login.LoginUserAccountResponse, error)
	RegisterUserAccount(ctx context.Context, in *register.RegisterUserAccountRequest, opts ...grpc.CallOption) (*register.RegisterUserAccountResponse, error)
}

type identityProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityProviderClient(cc grpc.ClientConnInterface) IdentityProviderClient {
	return &identityProviderClient{cc}
}

func (c *identityProviderClient) LoginUserAccount(ctx context.Context, in *login.LoginUserAccountRequest, opts ...grpc.CallOption) (*login.LoginUserAccountResponse, error) {
	out := new(login.LoginUserAccountResponse)
	err := c.cc.Invoke(ctx, "/pb.IdentityProvider/LoginUserAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderClient) RegisterUserAccount(ctx context.Context, in *register.RegisterUserAccountRequest, opts ...grpc.CallOption) (*register.RegisterUserAccountResponse, error) {
	out := new(register.RegisterUserAccountResponse)
	err := c.cc.Invoke(ctx, "/pb.IdentityProvider/RegisterUserAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityProviderServer is the server API for IdentityProvider service.
// All implementations must embed UnimplementedIdentityProviderServer
// for forward compatibility
type IdentityProviderServer interface {
	LoginUserAccount(context.Context, *login.LoginUserAccountRequest) (*login.LoginUserAccountResponse, error)
	RegisterUserAccount(context.Context, *register.RegisterUserAccountRequest) (*register.RegisterUserAccountResponse, error)
	mustEmbedUnimplementedIdentityProviderServer()
}

// UnimplementedIdentityProviderServer must be embedded to have forward compatible implementations.
type UnimplementedIdentityProviderServer struct {
}

func (UnimplementedIdentityProviderServer) LoginUserAccount(context.Context, *login.LoginUserAccountRequest) (*login.LoginUserAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUserAccount not implemented")
}
func (UnimplementedIdentityProviderServer) RegisterUserAccount(context.Context, *register.RegisterUserAccountRequest) (*register.RegisterUserAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUserAccount not implemented")
}
func (UnimplementedIdentityProviderServer) mustEmbedUnimplementedIdentityProviderServer() {}

// UnsafeIdentityProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityProviderServer will
// result in compilation errors.
type UnsafeIdentityProviderServer interface {
	mustEmbedUnimplementedIdentityProviderServer()
}

func RegisterIdentityProviderServer(s grpc.ServiceRegistrar, srv IdentityProviderServer) {
	s.RegisterService(&IdentityProvider_ServiceDesc, srv)
}

func _IdentityProvider_LoginUserAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(login.LoginUserAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServer).LoginUserAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.IdentityProvider/LoginUserAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServer).LoginUserAccount(ctx, req.(*login.LoginUserAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProvider_RegisterUserAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(register.RegisterUserAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServer).RegisterUserAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.IdentityProvider/RegisterUserAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServer).RegisterUserAccount(ctx, req.(*register.RegisterUserAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityProvider_ServiceDesc is the grpc.ServiceDesc for IdentityProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.IdentityProvider",
	HandlerType: (*IdentityProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginUserAccount",
			Handler:    _IdentityProvider_LoginUserAccount_Handler,
		},
		{
			MethodName: "RegisterUserAccount",
			Handler:    _IdentityProvider_RegisterUserAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idp_svc.proto",
}
